version: '3'
services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
  dogbin:
    image: dogbin/dogbin
    restart: always
    environment:
      - SESSION_KEY=${SESSION_KEY}
      - DB_LOCATION=/dogbin.xdb
      - HOST=${HOST}
      - SIMPLEANALYTICS=${SIMPLEANALYTICS}
    volumes:
      - ./dogbin.xdb:/dogbin.xdb
    expose:
      - 8080
    links:
      - "highlighter:highlighter"
      - "iframely:iframely"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dogbin.rule=Host(`${HOST}`)"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ && echo 'working fine'"]
      interval: 5s
      timeout: 5s
      retries: 3
  highlighter:
    image: dogbin/highlighter
    restart: always
    labels:
      - "traefik.enable=false"
  iframely:
    image: dogbin/iframely
    restart: always
    environment:
      - PORT=80
      - HOST=iframely.docker.localhost
      - BASE_APP_URL=https://${HOST}
    expose:
      - 80
    volumes:
      - ./iframely.config.js:/iframely/config.local.js
    command: server.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iframely.rule=Host(`${HOST}`) && PathPrefix(`/r/`)"
  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=10
      - AUTOHEAL_START_PERIOD=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
