version: '3'
services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.reverse-proxy.rule=Host(`traefik.docker.localhost`)"
  dogbin:
    build: .
    image: dogbin/dogbin
    environment:
      - SESSION_KEY=fc028d9226d5616261dbd69f13cfee4f
      - DB_LOCATION=/dogbin.xdb
      - HOST=l.del.dog
      - SIMPLEANALYTICS=false
    volumes:
      - ./dogbin.xdb:/dogbin.xdb
    expose:
      - 8080
    links:
      - "highlighter:highlighter"
      - "iframely:iframely"
    labels:
      - "traefik.http.routers.dogbin.rule=Host(`${HOST}`)"
  highlighter:
    build: microservices/highlighter/
    image: dogbin/highlighter
    labels:
      - "traefik.http.routers.highlighter.rule=Host(`highlighter.docker.localhost`)"
  iframely:
    image: dogbin/iframely
    environment:
      - PORT=80
      - HOST=iframely
    expose:
      - 80
    volumes:
      - ./iframely.config.js:/iframely/config.local.js
    command: server.js
    labels:
      - "traefik.http.routers.iframely.rule=Host(`iframely.docker.localhost`) || (Host(`${HOST}`) && PathPrefix(`/r/`))"