version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
  dogbin:
    image: dogbin/dogbin
    restart: always
    environment:
      - SESSION_KEY=${SESSION_KEY}
      - DB_LOCATION=/dogbin.xdb
      - HOST=${HOST}
      - SIMPLEANALYTICS=${SIMPLEANALYTICS}
    volumes:
      - ./dogbin.xdb:/dogbin.xdb
    expose:
      - 8080
      - 9090
    links:
      - "highlighter:highlighter"
      - "iframely:iframely"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dogbin.rule=Host(`${HOST}`)"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ && echo 'working fine'"]
      interval: 5s
      timeout: 5s
      retries: 3
  highlighter:
    image: dogbin/highlighter
    restart: always
    labels:
      - "traefik.enable=false"
  iframely:
    image: dogbin/iframely
    restart: always
    environment:
      - PORT=80
      - HOST=iframely.docker.localhost
      - BASE_APP_URL=https://${HOST}
    expose:
      - 80
    volumes:
      - ./iframely.config.js:/iframely/config.local.js
    command: server.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iframely.rule=Host(`${HOST}`) && PathPrefix(`/r/`)"
  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=10
      - AUTOHEAL_START_PERIOD=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    volumes:
      - ./deployment/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deployment/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}`)"
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"